version: '3.7'

services:
  postgres:
    container_name: postgres-container
    image: postgres:11-alpine
    ports: 
      - "5432:5432"
    volumes: 
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dev
    restart: always
    networks: 
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql: {}
