version: "3.7"

services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks: 
      - default

volumes:
  mongodb:

networks:
  default:
    driver: "bridge"