version: '3.7'

services:
  postgres:
    container_name: postgres-container
    image: 'bitnami/postgresql'
    ports: 
      - '5432:5432'
    volumes: 
      - 'postgresql:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=clean
    restart: always
    networks: 
      - app-net

  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - '8080:8080'
    restart: always
    networks: 
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql:
    driver: local
